---
# tasks file for node-exporter
- name: Check if node-exporter exists
  command: "{{ node_exporter_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: node_exporter_check

- name: Download node-exporter
  unarchive:
    src: "{{ node_exporter_url }}"
    dest: "/tmp"
    remote_src: true
    mode: 0755

- name: Move node_exporter binary into place
  copy:
    src: "/tmp/node_exporter-1.8.2.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart node_exporter

- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /sbin/nologin

- name: Copy the node_exporter systemd unit file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
  register: node_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter
  when: node_exporter_service is changed

- name: Ensure node_exporter is running and enabled at boot.
  service:
    name: node_exporter
    state: started
    enabled: true