---
- name: Download postgres-exporter
  get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v0.15.0/postgres_exporter-0.15.0.linux-amd64.tar.gz"
    dest: "/tmp/postgres_exporter.tar.gz"

- name: Extract postgres-exporter
  unarchive:
    src: "/tmp/postgres_exporter.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Rename postgres-exporter directory
  command: mv /opt/postgres_exporter-0.15.0.linux-amd64 /opt/postgres_exporter

- name: Create postgres_exporter user
  user:
    name: postgres_exporter
    system: yes
    shell: /sbin/nologin

- name: Create postgres-exporter configuration file
  copy:
    src: postgres_exporter.env
    dest: /opt/postgres_exporter/postgres_exporter.env
    owner: postgres_exporter
    group: postgres_exporter

- name: Copy systemd unit
  copy:
    src: postgres-exporter.service
    dest: /etc/systemd/system/postgres-exporter.service
  notify:
    - Daemon-reload
    - Restart postgres-exporter



