---
# vars file for node-exporter
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_host: ''
node_exporter_port: 9100
node_exporter_options: ''