---
# tasks file for prometheus
- name: Check if prometheus exists
  command: "{{ prometheus_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: prom_check

- name: Download prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "/tmp"
    remote_src: true
    mode: 0755

- name: Move prom binary into place
  copy:
    src: "/tmp/prometheus-2.55.0.linux-amd64/prometheus"
    dest: "{{ prometheus_bin_path }}"
    mode: 0755
    remote_src: true
  notify: restart prometheus

- name: Create prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin

- name: Create dir for tsdb
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: prometheus
    group: prometheus

- name: Create confs dirs
  file:
    path: "{{ prometheus_conf_dir }}"
    state: directory
    owner: prometheus
    group: prometheus

- name: Copy conf file
  copy:
    src: prometheus.yml
    dest: "{{ prometheus_conf_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus

- name: Copy prometheus systemd unit file.
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
  register: prometheus_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart prometheus
  when: prometheus_service is changed

- name: Ensure prometheus is running and enabled at boot.
  service:
    name: prometheus
    state: started
    enabled: true